config/routes.rb
Rails.application.routes.draw do
  get 'scots/new'

  get 'lawnbowls/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'team'    => 'scots#team'
  get 'name'    =>  'lawnbowl#name'
  get 'gallery' => 'static_pages#gallery'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'shelfhallpark'     => 'static_pages#shelfhallpark'
  get 'saddleworthroad'   => 'static_pages#saddleworthroad'
  
  
  get 'akroydonvictoriabowlingclub'   => 'static_pages#akroydonvictoriabowlingclub'
  get 'akroydpark'   => 'static_pages#akroydpark'
  get 'alanpark'    => 'static_pages#alanpark'
  get 'albionbowlingclub'   => 'static_pages#albionbowlingclub'
  get 'bailiffbridgeclub'   => 'static_pages#bailiffbridgeclub'
  get 'bradshawparl'    => 'static_pages#bradshawparl'
  get 'brighousesportsclub'   => 'static_pages#brighousesportsclub'
  get 'calderholmespark'    => 'static_pages#calderholmespark'
  get 'centrevalepark'   =>  'static_pages#centrevalepark'
  get 'crossleyssportground'    => 'static_pages#crossleyssportground'
  get 'crowwoodpark'    => 'static_pages#crowwoodpark'
  get 'ellandcricketathetic'    => 'static_pages#ellandcricketathetic'
  get 'elland'    => 'static_pages#elland'
  get 'greenroyd'   => 'static_pages#greenroyd'
  get 'halifax'   => 'static_pages#halifax'
  get 'heptonstall'   => 'static_pages#heptonstall'
  get 'hillcrest'   => 'static_pages#hillcrest'
  get 'hipperholme'   => 'static_pages#hipperholme'
  get 'hollins'   => 'static_pages#hollins'
  get 'hove'    => 'static_pages#hove'
  get 'homefield'   => 'static_pages#homefield'
  get 'kingstonsocialclub'    => 'static_pages#kingstonsocialclub'
  get 'green'   => 'static_pages#green'
  get 'leemillroad'  => 'static_pages#leemillroad'
  get 'mixenden'    => 'static_pages#mixenden'
  get 'norland'  => 'static_pages#norland'
  get 'northowram'    => 'static_pages#northowram'
  get 'outlane'   => 'static_pages#outlane'
  get 'pellon'    => 'static_pages#pellon'
  get 'rastrick'    => 'static_pages#rastrick'
  get 'ripponden'   => 'static_pages#ripponden'
  get 'stainland'  => 'static_pages#stainland'
  get 'shroggs'    => 'static_pages#shroggs'
  get 'siddal'    => 'static_pages#siddal'
  get 'sowerby'   => 'static_pages#sowerby'
  get 'spring'    => 'static_pages#spring'
  get 'wadworth'    => 'static_pages#wadworth'
  get 'walsden'   => 'static_pages#walsden'
  get 'wellseley'   => 'static_pages#wellseley'
  get 'west'    => 'static_pages#west'
  get 'wharf'   => 'static_pages#wharf'
  get 'woodvale'    => 'static_pages#woodvale'
  get 'errory'   => 'static_pages#errory'
  get 'results'  => 'static_pages#results'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
   resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="container-fluid">
  <div class="row">
    <div class="footer">
    <a href="#"> Copyright &copy; Katie Watson</a>
      <p>Bowling green locations - Assingment Two  CS2512, CS2514 Advanced Web Application Development</p>
    </div>
  </div>
</footer>
   

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-fixed-top">
     

<!-- Navagation Bar -->
        <nav class="navbar navbar-default">
          <div class="headcontainer-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>                        
              </button>
              
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
              <ul class="nav navbar-nav">
              
             
            
                    <li><%= link_to "Club Bowls", root_path %></li>
                    <li><%= link_to "Lawns", gallery_path %></li>
                     <li><%= link_to "Results", about_path %></li>
                    <% if logged_in? %>
                      <li><%= link_to "Users", users_path %></li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                          Account <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                          <li><%= link_to "Profile", current_user %></li>
                          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                          <li class="divider"></li>
                          <li>
                            <%= link_to "Logout", logout_path, method: "delete" %>
                          </li>
                        </ul>
                      </li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
        
        

      </ul>
                
            
              </ul>
            </div>
          </div>
        </nav>
  </nav>
  

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all","data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>

</style>
  </head>
<body>

  
  <%= render 'layouts/header' %>
  
        
                            

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      

      <%= yield %>
      
   


<%= render 'layouts/footer' %>
</body>

    

       <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %> 
      
      
</html>